title: NLP with Python
description: NLP is a discipline where computer science, artificial intelligence and cognitive logic are intercepted, with the objective that machines can read and understand our language for decision making
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
