title: NLP Course
description: Free hands-on course with the implementation (in Python) and description of several Natural Language Processing (NLP) algorithms and techniques
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
